### ISSUE TITLE
Error: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by bavella1** [jdahlblom/DCSFlightpanels#265]
Hello - I´m new to dcsflightpanels and would like to ask for help with this (for me) very first problem: 
I try to program a Saitek-Radio-Panel wich should send keystrokes "1" and "2" for each increment step on one of the rotarys and get this error:

_2022-12-31 20:14:07.5024|Error|System.IndexOutOfRangeException: Index was outside the bounds of the array.|Index was outside the bounds of the array.    at NonVisuals.BindingClasses.Key.KeyBindingBase.ParseSettingV1(String config)
   at NonVisuals.BindingClasses.Key.KeyBindingPZ69.ImportSettings(String settings)
   at NonVisuals.Radios.RadioPanelPZ69Emulator.ImportSettings(GenericPanelBinding genericPanelBinding)
   at NonVisuals.Panels.GamingPanel.ProfileEvent(Object sender, ProfileEventArgs e)
   at NonVisuals.BindingMappingManager.SendBinding(String hidInstance)
   at DCSFlightpanels.ProfileHandler.PanelEvent(Object sender, PanelEventArgs e)
   at NonVisuals.EventArgs.AppEventHandler.PanelEvent(Object sender, String hidInstance, HIDSkeleton hidSkeleton, PanelEventType panelEventType)
   at DCSFlightpanels.MainWindow.CreatePanel(HIDSkeleton hidSkeleton)_

![1](https://user-images.githubusercontent.com/121762705/210178384-89a674ad-cc27-4b0f-a29e-b74425da73ca.jpg)

Hardware used:
- Saitek/Logitech Multipanel
- Saitek/Logitech Radiopanel
- Elgato Streamdeck
- CPU 12.700K, 64 GB DDR4, RTX 3090Ti, 
Attempted solutions:
- tried to program "1" and "2" on the rotary of the Mulitpanel - this works
- tried to program "1" on the AP-Button of the Radiopanel - get the error
- switched of the autostart of the Elgato-Software, rebooted and checked no Elgatosoftware is running - get the error, so that can be ruled out

DCSBios is not used.
DCSFlightpanel is running out of the folder wich I copied to ...\Saved Games\DCS.openbeta\DCSFlightpanels_x64_4.6.8365.1
There was no setup.exe or something similar so the folder is just the unziped download (7zip was used).

THX in advance for your help!

**Comment by jdahlblom** [comment]
Fixed in v4.6.8402.1.
